# Generated by Django 4.2.16 on 2024-10-16 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FireRiskForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region_name', models.CharField(max_length=100)),
                ('risk_level', models.CharField(choices=[('low', '낮음'), ('medium', '중간'), ('high', '높음')], max_length=10)),
                ('forecast_date', models.DateField()),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('wind_speed', models.FloatField()),
                ('precipitation', models.FloatField()),
            ],
        ),
    ]
